version: '3.9'

# from https://docs.docker.com/registry/deploying/

services:
  registry:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - 5000:5000
    volumes:
      - /config/nginx/nginx.conf:/etc/nginx/nginx.conf
