version: '3.9'

# from https://docs.docker.com/registry/deploying/

services:
  registry:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - 80:5000
    volumes:
      - /config/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - shared

networks:
  default:
    name: shared
    external: true
