version: '3'
services:
  dns:
    restart: always
    image: easypi/dnsmasq-arm:latest
    volumes:
      - /config/dns/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    cap_add:
      - NET_ADMIN
